name: Build ASP Net Container

on:
  push:
    branches: [ "dev", "8-setup-azure-resources-and-cicd" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
  

    steps:
      #Check out repo
      - name: Checkout repository
        uses: actions/checkout@v3
      
      #Setup up environment
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x.x'
      
      #Restore Dependencies
      - name: Restore Dependencies
        run: nuget restore ./VCASoftware.Evaluation.AspNet/VCASoftware.Evaluation.AspNet.sln

      - name: Dotnet Build
        run: dotnet build ./VCASoftware.Evaluation.AspNet/VCASoftware.Evaluation.AspNet.sln

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image - ASP AspNet
        if: | 
            github.event_name != 'pull_request'
        id: build-and-push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: 'aspnet_image'
          registry: ${{ env.REGISTRY }}
          dockerfile: ./VCASoftware.Evaluation.AspNet/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest
      
      #Azure Login
      - name: Log in to Azure
        if: | 
          github.event_name != 'pull_request'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      #Deploy Container to Azure
      #enable
      - name: Build and deploy Container App
        if: | 
          github.event_name != 'pull_request'
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/alcantaramark/aspnet_image:latest
          containerAppName: vcasoftware-test-aspnet
          resourceGroup: vcasoftware-test
    
