# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build ASP Classic Container

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  
jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./VCASoftware.Evaluation.AspClassic
  

    steps:
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image - ASP Classic
        if: | 
            github.event_name != 'pull_request'
        id: build-and-push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: 'aspclassic_image'
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          labels: 'latest'
      
          
    
